### ISSUE TITLE
attrs: Must contain the property specified by `idAttribute`!

### ISSUE THREAD

**Issue by warnew** [js-data/js-data-angular#157]
I' have a json like so:

```
    {
       "idenyek" : [
       {
        "faj"   : "Gímszarvas",
        "id"    : "1",
        "type"  : "nagyvad",
        "group" : "bika",
        "dates" : [{"starts": "09.01.", "ends": "01.31."}]},

     ....

     }
```

And a resource: 

```
.factory('Seasons', function(DS) {
  var Seasons = DS.defineResource({
    name: 'idenyek',
    maxAge: 900000,
    deleteOnExpire: 'aggressive',
    storageMode: 'localStorage',    
  });
  return Seasons;
});
```

And an error message: 

Error: DS.inject(idenyek, attrs): attrs: Must contain the property specified by `idAttribute`!

I tried to add idAttribute to the definition, tried to do some beforeInject debugging without luck... what am I missing?

**Comment by YossiH** [comment]
I attempted the example above:

{
  "faj"   : "Gímszarvas",
  "id"    : "1",
  "type"  : "nagyvad",
  "group" : "bika",
  "dates" : [{"starts": "09.01.", "ends": "01.31."}]}
}

and received an error:  Unexpected token }

any clues?

**Comment by cah-danielmullins** [comment]
You have an extra bracket here:


 "ends": "01.31."}]}

Should be: "ends": "01.31" }]

Thanks,

Daniel Mullins

On Feb 8, 2015, at 11:54, YossiH <notifications@github.com<mailto:notifications@github.com>> wrote:


I attempted the example above:

{
"faj" : "Gímszarvas",
"id" : "1",
"type" : "nagyvad",
"group" : "bika",
"dates" : [{"starts": "09.01.", "ends": "01.31."}]}
}

and received an error: Unexpected token }

any clues?

—
Reply to this email directly or view it on GitHub<https://github.com/js-data/js-data-angular/issues/157#issuecomment-73422300>.

_________________________________________________

This message is for the designated recipient only and may contain privileged, proprietary
or otherwise private information. If you have received it in error, please notify the sender
immediately and delete the original. Any other use of the email by you is prohibited.

Dansk - Deutsch - Espanol - Francais - Italiano - Japanese - Nederlands - Norsk - Portuguese - Chinese
Svenska: www.cardinalhealth.com/legal/email

**Comment by YossiH** [comment]
Never mind.. it was the extra curly after the dates array. This worked ok:

[
    {
        "faj" : "Gímszarvas",
        "id" : "1",
        "type" : "nagyvad",
        "group" : "bika",
        "dates" : [{"starts": "09.01.", "ends": "01.31."}]
    },
    {
        "faj" : "Gímszarvas",
        "id" : "2",
        "type" : "nagyvad",
        "group" : "bika",
        "dates" : [{"starts": "09.01.", "ends": "01.31."}]
    }
]
