### ISSUE TITLE
loadRelations new (broken?) behaviour from angular-data 1.4.3+

### ISSUE THREAD

**Issue by m3l7** [js-data/js-data-angular#293]
hello,

I have a one-to-many relationship in my project: one category, multiple videos.
In angular-data 1.4.2, I'm doing something like this:

      VideoModel.findAll().then(function(vids){
         vids.forEach(function(vid){
            VideoModel.loadRelations(vid,['category']);
         });
      });

category model in videos is populated AND videos array in category is populated.

Starting from 1.4.3 videos array in category is not filled anymore.
Is it a correct behaviour?

**Comment by drakson** [comment]
I made a pull request long time ago to fix loading relations in arrays.

https://github.com/jmdobry/angular-data/pull/251

Maybe this could help you.

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-data, etc, relevant console logs/error, detailed code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-data).
