### ISSUE TITLE
Error: task.inject: "attrs" must be an object or an array!

### ISSUE THREAD

**Issue by RickCarlino** [js-data/js-data-angular#325]
I defined the following resource:

```coffeescript
Task = DS.defineResource
  name: "task"
  endpoint: 'tasks'
  basePath: '/api'
  idAttribute: "_id"
```

and in my controller the following return `Error: task.inject: "attrs" must be an object or an array!`:

```coffeescript
      Task.save(task._id)
    # OR
      Task.save(task._id, {info: task.info})
```

**Comment by RickCarlino** [comment]
This is on version `2.2.3`, by the way.

**Comment by jmdobry** [comment]
`Task.save(task._id)` will basically serialize `task` and send it to your server, expecting back the updated `task` that has the same `_id` (an object that has a primary key, hence the error `"attrs" must be an object`). 

`Task.save(task._id, {info: task.info})` will do the exact same thing, as `{info: task.info}` is not any sort of valid option. Perhaps you're looking for `Task.update(task._id, {info: task.info})`? See also [`DS#save`](http://www.js-data.io/docs/dssave), [`DS#update`](http://www.js-data.io/docs/dsupdate).

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, js-data, js-data-angular, etc., relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by RickCarlino** [comment]
I had actually already tried `Task.update(task._id, {info: task.info})` with identical results. Here is the stack trace:

```
 Error: task.inject: "attrs" must be an object or an array!
    at DS.inject (js-data/js-data.js?body=1:4645:12)
    at DS.inject (js-data-angular/js-data-angular.js?body=1:242:38)
    at js-data.js?body=1:5571:29
    at deferred.promise.then.wrappedCallback (/angular.js?body=1:11486:81)
    at deferred.promise.then.wrappedCallback (/angular.js?body=1:11486:81)
    at http://0.0.0.0:3000/assets/angular/angular.js?body=1:11572:26
    at Scope.$get.Scope.$eval (angular.js?body=1:12596:28)
    at Scope.$get.Scope.$digest (angular.js?body=1:12408:31)
    at Scope.$get.Scope.$apply (angular.js?body=1:12700:24)
    at done (angular.js?body=1:8288:45)
```

I will move further discussion to the mailing list.
