### ISSUE TITLE
Does js-data support embeded objects like no-sql?

### ISSUE THREAD

**Issue by raygerami** [js-data/js-data-angular#326]
Hi,
I was wondering if js-data supports embeded objects and would not confuse it with parent/foreign-key relation. i.e. our back-end db supports embeded objects like this
user = {
name: {
  firstname:'',
  lastname: '',
  title:''
}
}
thanks

**Comment by jmdobry** [comment]
I'm not sure what you mean by "supports". Is there a certain feature surrounding nested objects that you're looking for? It certainly doesn't prevent you from having whatever kind of nested objects you want.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).
