### ISSUE TITLE
Get endpoint or get resource name instance method

### ISSUE THREAD

**Issue by gtelljohann** [js-data/js-data-angular#341]
Hi, I'm trying to have several resources extend another, and one of the methods I want to generalize is a get URL method, but I'm having trouble figuring out how to do something like `return this.getEndpoint()` or `return '/api/' + this.resourceName() + '/' + this._id`.  

I noticed there is `DSHttpAdapter.getEndpoint()` method, but it requires access to the whole resource rather than just the instance.  Is there a way I'm missing that I could use to do this?  Or since it's a fairly simple function, should I just copy it for now?

Thanks!

**Comment by jmdobry** [comment]
In what context is your generalized method executing? What is `this`?

**Comment by gtelljohann** [comment]
This would be one of the instance methods on the resource, so `this` would be the individual resource instance.  Does that make sense?  So in my case, groups are being extended by pairs, teams, etc. so I would want to call `pairInstance.url()` and get the endpoint for that resource instance without having to define a separate function for each different type of group.

**Comment by jmdobry** [comment]
```javascript
angular.extend(DS.defaults, {
  afterCreateInstance: function (Resource, instance) {
    // "instance.kind" will only be accessible via "instance.kind"
    // won't be enumerated
    // won't be JSONified
    // Object.defineProperty doesn't work like this in IE8
    Object.defineProperty(instance, 'kind', {
      value: Resource.name
    });
  },
  methods: {
    url: function () {
      console.log(this.kind); // "user", "comment", etc.
      // return url based on "this.kind"
    }
  }
});
```

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by gtelljohann** [comment]
Cool, looks good, thanks!
